# Generated by Django 4.0.4 on 2022-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
